---
title: "painting-4"
output: html_document
---

```{r}
library(knitr)
library(tidyverse)
library(ggplot2)
```

```{r}
my_theme <- function(base_size = 12, base_family = "Helvetica"){
    theme_minimal() +
    theme(axis.title.y = element_blank(),axis.title.x = element_blank(),
    plot.title = element_text(face="bold", size=16),
    axis.text = element_blank(),
    plot.background = element_rect(fill = 'white',color=NA),
    panel.grid = element_blank(),
    legend.position = 'None', legend.title = element_blank(),
    aspect.ratio = 1)
}

```



*Plot 4 outline*:

plot base: done
plot lines: done
rectangles:
line dots:

```{r}
#| warning: false
set.seed(1)

rectangles <- data.frame(
  xmin = c(-0.5, 2.5, 4, 6, 7.5),
  xmax = c(1, 3.5, 6, 7.5, 9.7),
  ymin = c(7.5, 0, 7.5, .5, 4),
  ymax = c(10, 4, 7.5, 2, 10),
  color = c("#E8B600", "white", "white", "#CC0000", "white")
)


vertical_lines <- data.frame(
  x = c(0.75, 2.5, 6, 6.5, 9, 9.7),
  y = rep(10, 6)
)


horizontal_lines <- data.frame(
  x = c(10, 10, 10, 10, 10, 10, 10, 10),
  y = c(0.2, 1.3, 3.25, 4, 5.75, 6.5, 8.5, 9.7)
)


ggplot() +
  geom_segment(data = vertical_lines, aes(x = x, y = -0.5, xend = x, yend = y), color = "#E8B600", size = 2) +
  geom_segment(data = vertical_lines, aes(x = 1.2, y = 0.2, xend = 1.2, yend = y), color = "#E8B600", size = 2) +
  geom_segment(data = vertical_lines, aes(x = 0.5, y = 6.5, xend = 0.5, yend = y), color = "#E8B600", size = 2) +
  geom_segment(data = vertical_lines, aes(x = 6.5, y = 5.75, xend = 6.5, yend = 6.5), color = "white", size = 2) +
  geom_segment(data = vertical_lines, aes(x = 7.5, y = 3.25, xend = 7.5, yend = 5.75), color = "#E8B600", size = 2) +
  geom_segment(data = horizontal_lines, aes(x = -0.5, y = y, xend = x, yend = y), color = "#E8B600", size = 2) +
  geom_segment(data= horizontal_lines, aes(x=-0.5, y=2.75, xend=0.75, yend=2.75), color = "#E8B600", size = 2) +
  geom_segment(data= horizontal_lines, aes(x=-0.5, y=2, xend=0.75, yend=2), color = "#E8B600", size = 2) +
  geom_segment(data= horizontal_lines, aes(x=-0.5, y=1, xend=0.75, yend=1), color = "#E8B600", size = 2) +
  geom_segment(data= horizontal_lines, aes(x= 0.75, y=2.5, xend=6.5, yend=2.5), color = "#E8B600", size = 2) +
  coord_cartesian(xlim = c(0, 10), ylim = c(0, 10)) +
  scale_fill_identity() +
  my_theme()
```

