---
title: "Proposal"
format: html
editor: visual
---

**High level goal**: Our main goal with this project is to explore how Mondrian’s art can be illustrated and transformed with ggplot2.

**A one to two paragraph description of your goals, including your motivation.**

We hope to explore the relationships between Mondrian's works by transforming each piece into the next. We’ll do this by animating the process of expanding boxes, changing positions and colors. Our motivation for this project stems from our fascination with Mondrian's ability to convey aesthic meanings through minimalistic compositions, along with our desire to learn how to animate with ggplot2, something none of us have yet explored.

One of the major goals we have while working on this project is to offer a new perspective on interpreting art with data visualization using ggplot2. By working on animating the transormation of one piece into a another we hope to drastically increase our skills in the visualization field of R while also visualizing Mondrian's artistic journey and expertise through animating expanding boxes and changing positions. We hope that this process will help us uncover any patterns in Mondrian's work and help us better understand the thought process Mondrian had while creating his work.

**A weekly “plan of attack” outlining your steps to complete your project and including the team member(s) assigned to that task.**

-   [Week 1]{.underline} (March 20 - March 27): Work on proposal

    -   Lara: high-level goal

    -   Ishrit: description of goals

    -   Sophie: weekly plan of attack

    -   Tahsin: organization of project repo

-   [Week 2]{.underline} (March 27 - April 3): Edit proposal / make adjustments

    -   We will discuss feedback as a group, and whoever is most comfortable with that section will make edits

-   [Week 3]{.underline} (April 3 - 10): Start creating our own dataset / experiment with gganimate

    -   Each person will start with an image and try to create datasets:

        -   Team member #1: image 1 + research gganimate

        -   Team member #2: image 2

        -   Team member #3: image 3

        -   Team member #4: image 4

-   [Week 4]{.underline} (April 10 - 17): Grind out the project

    -   Team members will focus on their respective images

    -   Also, each team member will be responsible in creating the 'animation' data for the transitions between their image and another

-   [Week 5]{.underline} (April 17 - 24): Focus on debugging (slow down a bit for tests)

-   [Week 6]{.underline} (April 24 - May 1st): FINISH PROJECT AND PRESENTATION

*Note: For the future weeks, tasks will be split up more accurately later.*

**The final organization of your project repository. This means describing the project organization in your proposal as well as implementing that organization in your repo. Create any folders needed and place a `README.md` in each folder explaining what goes in there.**
