```{r}

library(tidyverse)
library(gganimate)
```

```{r}

my_theme <- function(base_size = 12, base_family = "Helvetica"){
    theme_minimal() +
    theme(axis.title.y = element_blank(),axis.title.x = element_blank(),
    plot.title = element_text(face="bold", size=16),
    axis.text = element_blank(),
    plot.background = element_rect(fill = 'ghostwhite',color='white'),
    panel.grid = element_blank(),
    legend.position = 'None', legend.title = element_blank())
}
```

```{r paris, fig.width = 5,  fig.height = 5}

set.seed(1)

rectangles = data.frame(
  xmin = c(2.5, -0.5, 9), 
  xmax = c(10.5, 2.5, 10.5), 
  ymin = c(3, -0.5, -0.5), 
  ymax = c(10.5, 3, 1.25),
  color = c("red", "blue", "yellow")
)


x_values = data.frame(x = c(2.5))
y_values = data.frame(y = c(3))

half_lines_horizontal = data.frame(
  x_start = c(-0.5, 9), 
  x_end = c(2.5, 10.5), 
  y = c(7, 1.25)
)

half_lines_vertical = data.frame(
  x = 9,             
  y_start = -0.5,       
  y_end = 3          
)

df |>
  ggplot() +
  geom_rect(data = rectangles, aes(xmin = xmin, xmax = xmax, ymin = ymin, 
                                   ymax = ymax, fill = as.factor(color))) +
  geom_vline(xintercept = x_values$x, linewidth = 4) +
  geom_hline(yintercept = y_values$y, linewidth = 4) + 
  coord_cartesian(xlim = c(0, 10), ylim = c(0, 10)) +
  geom_segment(data = half_lines_horizontal, aes(x = x_start, xend = x_end, y = y),
               linewidth = 4) +
  geom_segment(data = half_lines_vertical, aes(x = x, y = y_start, xend = x, 
                                               yend = y_end), linewidth = 4) +
  scale_fill_manual(values = c("blue" = "#255293", "red" = "#db0a16", 
                               "yellow" = "yellow")) +
  my_theme()
```
