```{r}

library(tidyverse)
library(gganimate)
```

```{r}

my_theme <- function(base_size = 12, base_family = "Helvetica"){
    theme_minimal() +
    theme(axis.title.y = element_blank(),axis.title.x = element_blank(),
    plot.title = element_text(face="bold", size=16),
    axis.text = element_blank(),
    plot.background = element_rect(fill = 'ghostwhite',color='white'),
    panel.grid = element_blank(),
    legend.position = 'None', legend.title = element_blank())
}
```

```{r ny, fig.width = 4,  fig.height = 5}
#| warning: false
set.seed(1)

rectangles <- data.frame(
  xmin = c(-0.5, 2.5, 4, 6, 7.5),
  xmax = c(1, 3.5, 6, 7.5, 9.7),
  ymin = c(7.5, 0, 7.5, .5, 4),
  ymax = c(10, 4, 7.5, 2, 10),
  color = c("#E8B600", "white", "white", "#CC0000", "white")
)


vertical_lines <- data.frame(
  x = c(1, 2.5, 3.5, 4, 6, 7.5, 8, 9.7),
  y = rep(10, 8)
)


horizontal_lines <- data.frame(
  x = c(10, 10, 10, 10),
  y = c(2, 4, 6, 7.5)
)


ggplot() +
  geom_rect(data = rectangles, aes(xmin = xmin, xmax = xmax, ymin = ymin, ymax = ymax, fill = color)) +
  geom_segment(data = vertical_lines, aes(x = x, y = -0.5, xend = x, yend = y), color = "black", size = 2) +
  geom_segment(data = horizontal_lines, aes(x = -0.5, y = y, xend = x, yend = y), color = "black", size = 4) +
  geom_segment(data= horizontal_lines, aes(x=1.1, y=0.3, xend=3.9, yend=0.3), color = "#1B6FAA", size = 3) +
  geom_segment(data= horizontal_lines, aes(x=2.6, y=0, xend=3.39, yend=0), color = "white", size = 3) +
  geom_segment(data= horizontal_lines, aes(x=6, y=0.4, xend=8, yend=0.4), color = "black", size = 3) +
  geom_segment(data= horizontal_lines, aes(x=6, y=-0.25, xend=8, yend=-.25), color = "black", size = 3) +
  geom_segment(data=horizontal_lines, aes(x=9.8, y=0.3, xend=10, yend=0.3), color="#CC0000", size = 3) +
  scale_fill_identity() +
  my_theme()
```